apiVersion: apps/v1
kind: Deployment
metadata: 
  name: redes-api-v1
  labels:
    app: redes-api-v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redes-api-v1
  template:
    metadata:
      labels:
        app: redes-api-v1
    spec:
      containers:
      - name: redes-api-v1
        image: redes-api-v1:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
