apiVersion: apps/v1
kind: Deployment
metadata: 
  name: v1-redes-api
  labels:
    app: v1-redes-api
  annotations:
    traffic.sidecar.istio.io/includeInboundPorts: ""
    traffic.sidecar.istio.io/excludeInboundPorts: "80,443"
    traffic.sidecar.istio.io/excludeOutboundIPRanges: ""
    sidecar.istio.io/inject: 'true'
spec:
  replicas: 3
  selector:
    matchLabels:
      app: v1-redes-api
  template:
    metadata:
      labels:
        app: v1-redes-api
    spec:
      containers:
      - name: v1-redes-api
        image: v1-redes-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: postgres-db-configmap
