apiVersion: v1
kind: Service
metadata:
  labels: 
    app: nginx-deploy
  name: nginx-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: nginx-deploy
  type: LoadBalancer