apiVersion: apps/v1
kind: Deployment
metadata: 
  name: redes-fastapi
  labels:
    app: redes-fastapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redes-fastapi
  template:
    metadata:
      labels:
        app: redes-fastapi
    spec:
      containers:
      - name: redes-fastapi
        image: tpe-redes-fastapi:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
