apiVersion: v1
kind: Service
metadata:
  labels: 
    app: redes-fastapi
  name: redes-fastapi-service
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: redes-fastapi
