apiVersion: v1
kind: Service
metadata:
  name: redes-api-v2-service
  labels: 
    app: redes-api-v2
spec:
  type: ClusterIP
  selector:
    app: redes-api-v2
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP