apiVersion: v1
kind: Service
metadata:
  name: v2-redes-api-service
  labels: 
    app: v2-redes-api
spec:
  type: ClusterIP
  selector:
    app: v2-redes-api
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP