apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
spec: 
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
      # The postgres container
      - name: postgres-db
        image: postgres:13

        # Pull the image from Docker Hub if not present locally
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 5432

        # Get the environment variables from a ConfigMap
        envFrom:
        - configMapRef:
            name: postgres-db-configmap
          
        # Mount the volume to persist the data in the container
        volumeMounts:
        - name: postgres-volume
          mountPath: /var/lib/postgresql/data

      
      volumes:
      - name: postgres-volume
        persistentVolumeClaim:
          claimName: postgres-pvc