apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    app: postgres-db
spec:
  accessModes:
    # Many pods can read/write to the same volume
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
