apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pvolume
  labels:
      app: postgres-db
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/db"